name: ci

on:
  pull_request:
    branches: '**'
  push:
    branches: main

env:
  CARGO_TERM_COLOR: always
  TOOLCHAIN: stable

jobs:
  ci:
    timeout-minutes: 10
    name: verify
    runs-on: ubuntu-latest

    # fail on rust warnings
    env:
      RUSTFLAGS: '-Dwarnings'

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: update rust version
        run: rustup update ${{ env.TOOLCHAIN }} && rustup default ${{ env.TOOLCHAIN }}

      - name: cache
        uses: Swatinem/rust-cache@v2

      - name: format
        run: cargo fmt --all

      - name: lint
        run: cargo clippy --all-targets --all-features

      - name: test
        run: cargo test --verbose

      - name: build
        run: cargo build --release --verbose
