name: Rust Project CI

on:
  pull_request:
    branches: '**'
  push:
    branches: main

env:
  CARGO_TERM_COLOR: always
  TOOLCHAIN: stable

jobs:
  ci:
    name: CI
    timeout-minutes: 15
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{matrix.os}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Update Toolchain
        run: |
          rustup update ${{ env.TOOLCHAIN }}
          rustup default ${{ env.TOOLCHAIN }}

      - name: Cache
        uses: Swatinem/rust-cache@v2

      - name: Format
        run: cargo fmt --all

      - name: Lint
        run: cargo clippy --all-targets --all-features

      - name: Tests
        run: cargo test --verbose

      - name: Build
        run: cargo build --release --verbose
